###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

mysql:
  image: mysql
  command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci',
            '--default-authentication-plugin=mysql_native_password']
  container_name: mysql
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=1
    - MYSQL_HOST=localhost
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
  ports:
    - 3306:3306
  volumes:
    - ../mysql:/var/lib/mysql
    - ./dev-scripts/populate_database.sh:/docker-entrypoint-initdb.d/populate_database.sh
    - ./dev-scripts/initial-database.sql:/dev-scripts/initial-database.sql

myapp-nginx:
  image: nginx:latest
  container_name: myapp-nginx
  volumes:
      - ../cakephp:/var/www/myapp
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8180:80"
  links:
   - myapp-php-fpm

myapp-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: myapp-php-fpm
  volumes:
    - ../cakephp:/var/www/myapp
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
  links:
    - mysql
